name: Generate GitHub Dashboard

on:
  schedule:
    - cron: "0 0 * * *"   # diário
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Export environment variables
        run: |
          echo "GITHUB_USERNAME=Domisnnet" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Generate Dashboard
        run: python generators/generate_dashboard.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if [ -f output/dashboard.png ]; then
            git add output/dashboard.png
            git commit -m "Atualiza dashboard premium" || echo "Sem alterações"
            git push
          else
            echo "Nenhuma imagem foi gerada."
          fi